### ISSUE TITLE
Too few arguments to function

### ISSUE THREAD

**Issue by dennismetz** [derhansen/fe_change_pwd#62]
Hi, I am getting the following error after upgrading from 10 to 11:

Too few arguments to function Derhansen\FeChangePwd\Middleware\ForcePasswordChangeRedirect::__construct(), 0 passed in /private/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3217 and at least 2 expected

TYPO3 11.5.x
PHP8.1
Apache
